### ISSUE TITLE
Support for non-string placeholders?

### ISSUE THREAD

**Issue by csicar** [yonigibbs/elm-i18next-gen#6]
`elm-i18next` is about to get support for non-string placeholders (https://github.com/ChristophP/elm-i18next/pull/27). (Reasons for implementing it are explained here: https://github.com/ChristophP/elm-i18next/issues/26)

Maybe `elm-i18next-gen` could also get support for it?

I'm not sure, what the best way would be to implement it. One idea might be:
- Add an option to the CLI e.g. `--custom-replacements` (similar to `--fallback`)
- Allow the user to specify the module, the translations are generated under

So if a user wants to user both `tr` generated functions and `customTr`, he could call `em-i18next-gen` twice: Once normally into the `Translations` namespace and once into the `CustomTranslations` namespace.

**Comment by yonigibbs** [comment]
Hey @csicar, thanks for reaching out. That does look like an awesome feature you've added into `elm-i18next`. Great work! Definitely agree it would be good for `elm-i18next-gen` to have it as well. Let's do it!

Thinking about the options... I definitely agree that this should be controlled by some command-line argument. I'm not sure the idea of making the user run the tool twice is the most ideal solution, esp because of `watch` mode. Ideally in that mode whenever you change the source JSON, you'd want the generated Elm code to be updated immediately for both the `tr` and `customTr` functions (assuming you're using both). And currently `watch` mode only runs once, with one given set of command-line arguments.

So how about instead we add some new argument called something like `translationType` (not sure about the name), which has three possible values:
* `default`: the current behaviour, i.e. generates functions which use the `tr` (or `trf`) functions.
* `custom`: generates functions which use the new `customTr` (or `customTrf`) functions.
* `both`: generates both sets of functions.

The problem with the third option of course is how to keep the two generated functions separate. One idea, as you suggest, is modules. Another is to name each function differently. e.g. if the JSON has an entry called `greet` then could we generate two functions: `greet` and `customGreet`? I'm not sure how intuitive that is, to be honest, but I'm also not sure if specifying different modules is any more intuitive.

Also the idea of having a `custom...` function could potentially lead to name clashes (e.g. if the JSON happened to also include an entry called `customGreet`). But I think we can handle that either as an error, or just naming the entry `customGreet_` or something like that to avoid the clash.

Do you have any thoughts on the above? Any ideas for naming of the args/options? It would be good to keep the naming in this tool consistent with whatever is used in `elm-i18next` itself (and its documentation).

@ChristophP, CC'ing you here in case you have any thoughts/suggestions.

Also, @csicar, is this something you'd like to contribute, or do you want me to do it?

**Comment by ChristophP** [comment]
Hi there, cool to see the new feature also on its way to be supported here. :-)
Just to let you know I've been holding of on releasing because I wanted to get feedback from @csicar  on the issue that is still open. I wanna give him a couple of more days. Other than that it is ready to release. @yonigibbs  feel free to give feedback as well.
https://github.com/ChristophP/elm-i18next/issues/26#issuecomment-744760662

**Comment by csicar** [comment]
> I'm not sure the idea of making the user run the tool twice is the most ideal solution, esp because of watch mode.

Yes, absolutely.

> I'm not sure how intuitive that is, to be honest, but I'm also not sure if specifying different modules is any more intuitive.

They avoid the naming problem, but aren't intuitive at all. The user would still need to choose different names when importing.

> Another is to name each function differently. e.g. if the JSON has an entry called greet then could we generate two functions

That seems like an excellent idea to me. How about generating both `tr` and `customTr` functions, where the `customTr` functions just have a `_` suffix?

**Comment by yonigibbs** [comment]
Cool, thanks @csicar and @ChristophP. Let's go with the option of generating the two sets of functions (if that's what the user supplies in cmd-line args). I'm not personally that keen on `_` suffix because it's not very clear what it means. If I came to a codebase and saw two functions: `greet` and `greet_` I would be a bit unsure what the difference is, and which one's which. I think that since the word `custom` is used in `elm-i18next`, I'd be tempted to stick with that as the distinguishing text when naming the functions. So for the moment I'm going to propose we stick with that, and in future (or if either of you disagree now) we can make the naming of the custom functions configurable through another command-line argument. Danger of command-line-argument overload notwithstanding :-)

I'll try to get round to this in the next few weeks. In the meantime if you have any suggestions for the argument names/values I suggested earlier, let me know.

**Comment by csicar** [comment]
`custom*` is fine as well. I think having one fixed, hard-coded prefix is absolutely fine.

I think we could even do without any CLI-Option, by always generating the `custom*` functions. That would mean no "cli-arg overload" and no extra work needed to use a `custom*` function.

> Also, @csicar, is this something you'd like to contribute, or do you want me to do it?

I totally missed that. Yes I'd be happy to help with implementing this feature :)

**Comment by yonigibbs** [comment]
Hey @csicar. I've already started working on this (sorry!) and am pretty close, so leave the implementation with me for now, if that's OK with you.

Re no cmd-line args... I'm tempted, but I think on balance I'll go for this being an opt-in feature turned on through cmd-line args. One reason is that otherwise we'd be forcing people to have to use a specific version of `elm-i18next`. A second reason is that if a user doesn't plan to use this new feature, it creates quite a lot of "noise" in their generated translation files (two functions per JSON entry instead of one).

**Comment by csicar** [comment]
> specific version of elm-i18next .

Yeah. that's a good point. Makes sense

 Yes. I'm absolutely happy with you implementing this. :) thank you!
